### ISSUE TITLE
Matrix build to Windows & MacOS

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-clickhouse#113]
```yaml
strategy:
  matrix:
    os: [ubuntu-latest]
    # os: [ubuntu-latest, macos-latest, windows-latest]
runs-on: ${{ matrix.os }}
```
